### ISSUE TITLE
Please fix blackjack New Game button

### ISSUE THREAD

**Issue by hiranmay1000** [hiranmay1000/personal-HTML-website#3] opened 2022-06-23 14:43 UTC
The algorithm's problem is that it stopped working after winning the game (got blackjack). Please review the game before editing the code.

**New Game Button is not working fix that**

![Screenshot 2022-06-23 201149](https://user-images.githubusercontent.com/97354423/175326670-26fc47e7-6743-471a-9d54-237478377e0a.png)
![Screenshot 2022-06-23 201129](https://user-images.githubusercontent.com/97354423/175326686-59c9894e-db3d-4454-af35-175bf83c8eb3.png)

**Comment by geamnegru** [comment] 2022-06-26 10:33
@hiranmay1000 check pull request for fix, the issue was caused by me when I changed in the file blackjack.js the lets with consts because it didn't let it update I suppose

**Comment by hiranmay1000** [comment] 2022-06-27 02:25
No! This bug was still there before your commit. Please visit into the website and check the game for a min.@Gamsti1337

**Comment by geamnegru** [comment] 2022-06-27 06:57
Good morning! Found the problem, you probably changed the ids of some elements and js didn't find them in the DOM and that means it can't change them. Gonna create a PR

**Comment by geamnegru** [comment] 2022-07-23 06:33
@hiranmay1000 can you close the issue?

**Comment by hiranmay1000** [comment] 2022-07-23 06:34
I'll do in a moment

**Closed as completed** 2022-07-23 08:28 UTC
Labels: bug, good first issue
